version: '3.9'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test-db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/posgresql/data
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - 'db'
      - 'rabbitmq'
    environment:
      JWT_SECRET: gigasecretkey
      PG_USER: user
      PG_PASSWORD: pass
      PG_PORT: 5432
      PG_DATABASE: test-db
      PG_HOST: db
      PORT: 5000
      RABBITMQ_HOST: rabbitmq
      DATABASE_URL: postgres://user:pass@db:5432/test-db
    restart: always
  client:
    build:
      context: ./client
    restart: always
    ports:
      - 80:80
    depends_on:
      - 'api'
  scraper:
    build: './scraper'
    restart: always
    environment:
      BROKER_HOST: 'rabbitmq'
    depends_on:
      - 'rabbitmq'
  rabbitmq:
    image: 'rabbitmq:3.10-management'
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always

volumes:
  pg_data:
